language: go

install:
  - go get -v github.com/davyxu/golog
  - go get -v github.com/davyxu/goobjfmt
  - go get -v github.com/davyxu/gosproto
  - go get -v github.com/golang/protobuf/proto

go:
  - 1.8

script:
  - go test -v github.com/davyxu/cellnet/example/echo_pb github.com/davyxu/cellnet/example/echo_sproto github.com/davyxu/cellnet/example/classicrecv github.com/davyxu/cellnet/example/sendclose github.com/davyxu/cellnet/example/gracefulexit

after_success:
  - bash <(curl -s https://codecov.io/bash)