language: go

install:
  - go get -v github.com/davyxu/golog
  - go get -v github.com/davyxu/goobjfmt

go:
  - 1.9

script:
  - go test -v github.com/davyxu/cellnet/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)